stages:
  - Build Images

Build backend:
  stage: Build Images
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t muarilioayrton/app-php-dio-backend:1.0 backend/.
    - docker push muarilioayrton/app-php-dio-backend:1.0

Build frontend:
  stage: Build Images
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t muarilioayrton/app-php-dio-frontend:1.0 frontend/.
    - docker push muarilioayrton/app-php-dio-frontend:1.0
  needs:
    - Build backend

Build Database:
  stage: Build Images
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t muarilioayrton/app-php-dio-database:1.0 database/.
    - docker push muarilioayrton/app-php-dio-database:1.0
  needs:
    - Build frontend